version: '2.1'
services:
  registry:
    image: andshl/notificationapp-registry
    build: Registry
    ports:
      - 8761:8761
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  gateway:
    image: andshl/notificationapp-gateway
    build: Gateway
    ports:
      - 8079:8079
    restart: always
    depends_on:
      - registry
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  email-notification-service:
    image: andshl/notificationapp-email-notification-service
    build: EmailNotificationService
    ports:
      - 8000:8000
    restart: always
    depends_on:
      - registry
      - gateway
    logging:
      options:
        max-size: "10m"
        max-file: "10"